package registry

import (
	"atlas-pos/portal/script"
	"atlas-pos/portal/script/discrete"
	"errors"
	"sync"
)

type ScriptRegistry struct {
	registry map[string]script.Script
}

var once sync.Once
var scriptRegistry *ScriptRegistry

func GetScriptRegistry() *ScriptRegistry {
	once.Do(func() {
		scriptRegistry = initRegistry()
	})
	return scriptRegistry
}

func initRegistry() *ScriptRegistry {
	s := &ScriptRegistry{make(map[string]script.Script)}
	s.addPortalScript(discrete.ChristmasOut2008{})
	s.addPortalScript(discrete.Advice00{})
	s.addPortalScript(discrete.Advice01{})
	s.addPortalScript(discrete.Advice02{})
	s.addPortalScript(discrete.Advice03{})
	s.addPortalScript(discrete.Advice04{})
	s.addPortalScript(discrete.Advice05{})
	s.addPortalScript(discrete.Advice06{})
	s.addPortalScript(discrete.Advice07{})
	s.addPortalScript(discrete.Advice08{})
	s.addPortalScript(discrete.Advice09{})
	s.addPortalScript(discrete.AdviceMap{})
	s.addPortalScript(discrete.AMatchMove2{})
	s.addPortalScript(discrete.Apq00{})
	s.addPortalScript(discrete.Apq01{})
	s.addPortalScript(discrete.Apq1{})
	s.addPortalScript(discrete.Apq02{})
	s.addPortalScript(discrete.Apq2{})
	s.addPortalScript(discrete.Apq3{})
	s.addPortalScript(discrete.ApqClosed{})
	s.addPortalScript(discrete.ApqDoor{})
	s.addPortalScript(discrete.AquaPQBoss0{})
	s.addPortalScript(discrete.AranTutorAloneX{})
	s.addPortalScript(discrete.AranTutorArrow0{})
	s.addPortalScript(discrete.AranTutorArrow1{})
	s.addPortalScript(discrete.AranTutorArrow2{})
	s.addPortalScript(discrete.AranTutorArrow3{})
	s.addPortalScript(discrete.AranTutorGuide0{})
	s.addPortalScript(discrete.AranTutorGuide1{})
	s.addPortalScript(discrete.AranTutorGuide2{})
	s.addPortalScript(discrete.AranTutorLost{})
	s.addPortalScript(discrete.AranTutorMono0{})
	s.addPortalScript(discrete.AranTutorMono1{})
	s.addPortalScript(discrete.AranTutorMono2{})
	s.addPortalScript(discrete.AranTutorMono3{})
	s.addPortalScript(discrete.AranTutorOut1{})
	s.addPortalScript(discrete.AranTutorOut2{})
	s.addPortalScript(discrete.AranTutorOut3{})
	s.addPortalScript(discrete.AriantAgit{})
	s.addPortalScript(discrete.AriantCastle{})
	s.addPortalScript(discrete.AriantQueens{})
	s.addPortalScript(discrete.AriantMount{})
	s.addPortalScript(discrete.AriantMount2{})
	s.addPortalScript(discrete.BabyPigOut{})
	s.addPortalScript(discrete.BalogEnd{})
	s.addPortalScript(discrete.BalogTemple{})
	s.addPortalScript(discrete.BedroomOut{})
	s.addPortalScript(discrete.CannonTuto06{})
	s.addPortalScript(discrete.CannonTuto07{})
	s.addPortalScript(discrete.CannonTuto09{})
	s.addPortalScript(discrete.CannonTuto10{})
	s.addPortalScript(discrete.CaptinsG00{})
	s.addPortalScript(discrete.CatPriestMap{})
	s.addPortalScript(discrete.ContactDragon{})
	s.addPortalScript(discrete.CurseForest{})
	s.addPortalScript(discrete.Davy2Hd1{})
	s.addPortalScript(discrete.Davy3Hd1{})
	s.addPortalScript(discrete.DavyNext0{})
	s.addPortalScript(discrete.DavyNext1{})
	s.addPortalScript(discrete.DavyNext2{})
	s.addPortalScript(discrete.DavyNext3{})
	s.addPortalScript(discrete.DavyNext4{})
	s.addPortalScript(discrete.DepartGoBack00{})
	s.addPortalScript(discrete.DepartGoBack01{})
	s.addPortalScript(discrete.DepartGoFoward0{})
	s.addPortalScript(discrete.DepartGoFoward1{})
	s.addPortalScript(discrete.DepartToKerning{})
	s.addPortalScript(discrete.DepartTopFloor{})
	s.addPortalScript(discrete.DepartTopOut{})
	s.addPortalScript(discrete.DojangExit{})
	s.addPortalScript(discrete.DojangNext{})
	s.addPortalScript(discrete.DojangTuto{})
	s.addPortalScript(discrete.DojangUp{})
	s.addPortalScript(discrete.Dracoout{})
	s.addPortalScript(discrete.DragonEggNotice{})
	s.addPortalScript(discrete.DragonEyes{})
	s.addPortalScript(discrete.DragonNest{})
	s.addPortalScript(discrete.EBoat1{})
	s.addPortalScript(discrete.EBoat2{})
	s.addPortalScript(discrete.Elevator{})
	s.addPortalScript(discrete.ElizaGarden{})
	s.addPortalScript(discrete.EndCow{})
	s.addPortalScript(discrete.EnterEarth00{})
	s.addPortalScript(discrete.EnterEarth01{})
	s.addPortalScript(discrete.EnterNautil{})
	s.addPortalScript(discrete.EnterTd{})
	s.addPortalScript(discrete.EnterAchter{})
	s.addPortalScript(discrete.EnterBackStreet{})
	s.addPortalScript(discrete.EnterDisguise0{})
	s.addPortalScript(discrete.EnterDisguise1{})
	s.addPortalScript(discrete.EnterDisguise2{})
	s.addPortalScript(discrete.EnterDisguise3{})
	s.addPortalScript(discrete.EnterDisguise4{})
	s.addPortalScript(discrete.EnterDisguise5{})
	s.addPortalScript(discrete.EnterDollcave{})
	s.addPortalScript(discrete.EnterDollWay{})
	s.addPortalScript(discrete.EnterEvanRoom{})
	s.addPortalScript(discrete.EnterFirstDH{})
	s.addPortalScript(discrete.EnterFourthDH{})
	s.addPortalScript(discrete.EnterGym{})
	s.addPortalScript(discrete.EnterInfo{})
	s.addPortalScript(discrete.EnterMagiclibrar{})
	s.addPortalScript(discrete.EnterMCave{})
	s.addPortalScript(discrete.EnterNepenthes{})
	s.addPortalScript(discrete.EnterPort{})
	s.addPortalScript(discrete.EnterRider{})
	s.addPortalScript(discrete.EnterRienFirst{})
	s.addPortalScript(discrete.EnterSecondDH{})
	s.addPortalScript(discrete.EnterThirdDH{})
	s.addPortalScript(discrete.EnterTraining{})
	s.addPortalScript(discrete.EnterWarehouse{})
	s.addPortalScript(discrete.EnterWitch{})
	s.addPortalScript(discrete.EvanEntrance{})
	s.addPortalScript(discrete.EvanFall{})
	s.addPortalScript(discrete.EvanFarmCT{})
	s.addPortalScript(discrete.EvanGarden0{})
	s.addPortalScript(discrete.EvanGarden1{})
	s.addPortalScript(discrete.EvanLivingRoom{})
	s.addPortalScript(discrete.EvanRoom0{})
	s.addPortalScript(discrete.EvanRoom1{})
	s.addPortalScript(discrete.EvanTalk00{})
	s.addPortalScript(discrete.EvanTalk01{})
	s.addPortalScript(discrete.EvanTalk02{})
	s.addPortalScript(discrete.EvanTalk10{})
	s.addPortalScript(discrete.EvanTalk11{})
	s.addPortalScript(discrete.EvanTalk20{})
	s.addPortalScript(discrete.EvanTalk21{})
	s.addPortalScript(discrete.EvanTalk40{})
	s.addPortalScript(discrete.EvanTalk41{})
	s.addPortalScript(discrete.EvanTalk42{})
	s.addPortalScript(discrete.EvanTalk50{})
	s.addPortalScript(discrete.EvanTalk60{})
	s.addPortalScript(discrete.ExitPuppeteer{})
	s.addPortalScript(discrete.Female00{})
	s.addPortalScript(discrete.FoxLaidyMap{})
	s.addPortalScript(discrete.GagaSuccess{})
	s.addPortalScript(discrete.Gendergo{})
	s.addPortalScript(discrete.GhostGateOpen{})
	s.addPortalScript(discrete.GlpqEnter{})
	s.addPortalScript(discrete.GlpqPortal0{})
	s.addPortalScript(discrete.GlpqPortal00{})
	s.addPortalScript(discrete.GlpqPortal1{})
	s.addPortalScript(discrete.GlpqPortal01{})
	s.addPortalScript(discrete.GlpqPortal2{})
	s.addPortalScript(discrete.GlpqPortal02{})
	s.addPortalScript(discrete.GlpqPortal3{})
	s.addPortalScript(discrete.GlpqPortal03{})
	s.addPortalScript(discrete.GlpqPortal4{})
	s.addPortalScript(discrete.GlpqPortal04{})
	s.addPortalScript(discrete.GlpqPortal5{})
	s.addPortalScript(discrete.GlpqPortal6{})
	s.addPortalScript(discrete.GlpqPortal7{})
	s.addPortalScript(discrete.GlpqPortalDummy{})
	s.addPortalScript(discrete.GlTutoMsg0{})
	s.addPortalScript(discrete.GoSecretRoom{})
	s.addPortalScript(discrete.GotoCastle{})
	s.addPortalScript(discrete.Gryphius{})
	s.addPortalScript(discrete.Guild1F00{})
	s.addPortalScript(discrete.Guild1F01{})
	s.addPortalScript(discrete.Guild1F02{})
	s.addPortalScript(discrete.Guild1F03{})
	s.addPortalScript(discrete.Guild1F04{})
	s.addPortalScript(discrete.GuildWaitingEnter{})
	s.addPortalScript(discrete.GuildWaitingExit{})
	s.addPortalScript(discrete.GuyFawkes0Esc{})
	s.addPortalScript(discrete.GuyFawkes0Floor{})
	s.addPortalScript(discrete.HalloweenEnter{})
	s.addPortalScript(discrete.HalloweenOmni1{})
	s.addPortalScript(discrete.HighPosition{})

	s.addPortalScript(discrete.InfoMiniMap{})
	s.addPortalScript(discrete.TutoChatNPC{})
	return s
}

func (s *ScriptRegistry) GetScript(name string) (*script.Script, error) {
	if val, ok := s.registry[name]; ok {
		return &val, nil
	}
	return nil, errors.New("unable to locate script")
}

func (s *ScriptRegistry) addPortalScript(handler script.PortalScript) {
	s.registry[handler.Name()] = script.NewScript(handler)
}
